# Generated by Django 4.1.4 on 2023-01-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='img',
            field=models.ImageField(default='aaaaaa', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
